

/* Create Tables */

CREATE TABLE COUNTRY
(
	COUNTRY_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '国id',
	COUNTRY_NAME VARCHAR(100) NOT NULL COMMENT '国名',
	COUNTRY_TOP_PAGE_URL VARCHAR(255) NOT NULL COMMENT '国トップページURL',
	DISPLAY_ORDER INT UNSIGNED NOT NULL COMMENT '表示順',
	IS_CRAWL_FAIL BOOLEAN NOT NULL COMMENT 'クロール失敗しているか',
	IS_DISPLAY BOOLEAN NOT NULL COMMENT '表示するか',
	LAST_UPDATE_DATETIME DATETIME COMMENT '最終取得日時',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時',
	REGISTER_TRACE VARCHAR(64) NOT NULL COMMENT '登録トレース',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時',
	UPDATE_TRACE VARCHAR(64) NOT NULL COMMENT '更新トレース',
	PRIMARY KEY (COUNTRY_ID)
) COMMENT = '国';


CREATE TABLE COUNTRY_PLAYER
(
	COUNTRY_PLAYER_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '国プレイヤーID',
	COUNTRY_ID INT UNSIGNED NOT NULL COMMENT '国ID',
	PLAYER_ID INT UNSIGNED NOT NULL COMMENT 'プレイヤーID',
	USER_ID VARCHAR(100) NOT NULL COMMENT 'ユーザID',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時',
	REGISTER_TRACE VARCHAR(64) NOT NULL COMMENT '登録トレース',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時',
	UPDATE_TRACE VARCHAR(64) NOT NULL COMMENT '更新トレース',
	PRIMARY KEY (COUNTRY_PLAYER_ID),
	CONSTRAINT UQ_country_player_country_user_id UNIQUE (COUNTRY_ID, USER_ID)
) COMMENT = '国プレイヤー';


CREATE TABLE COUNTRY_PROGRESS
(
	COUNTRY_PROGRESS_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '国進行状況id',
	COUNTRY_ID INT UNSIGNED NOT NULL COMMENT '国id',
	DISPLAY_ORDER INT UNSIGNED NOT NULL COMMENT '表示順',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時',
	REGISTER_TRACE VARCHAR(64) NOT NULL COMMENT '登録トレース',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時',
	UPDATE_TRACE VARCHAR(64) NOT NULL COMMENT '更新トレース',
	PRIMARY KEY (COUNTRY_PROGRESS_ID)
) COMMENT = '国進行状況';


CREATE TABLE COUNTRY_PROGRESS_DETAIL
(
	COUNTRY_PROGRESS_DETAIL_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '国進行状況詳細id',
	COUNTRY_PROGRESS_ID INT UNSIGNED NOT NULL COMMENT '国進行状況id',
	ITEM_NAME VARCHAR(20) NOT NULL COMMENT '項目名',
	ITEM_VALUE VARCHAR(1000) NOT NULL COMMENT '項目値',
	PRIMARY KEY (COUNTRY_PROGRESS_DETAIL_ID)
) COMMENT = '国進行状況詳細';


CREATE TABLE COUNTRY_RECRUITMENT
(
	COUNTRY_RECRUITMENT_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '国募集状況id',
	COUNTRY_ID INT UNSIGNED NOT NULL COMMENT '国id',
	DISPLAY_ORDER INT UNSIGNED NOT NULL COMMENT '表示順',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時',
	REGISTER_TRACE VARCHAR(64) NOT NULL COMMENT '登録トレース',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時',
	UPDATE_TRACE VARCHAR(64) NOT NULL COMMENT '更新トレース',
	PRIMARY KEY (COUNTRY_RECRUITMENT_ID)
) COMMENT = '国募集状況';


CREATE TABLE COUNTRY_RECRUITMENT_DETAIL
(
	COUNTRY_RECRUITMENT_DETAIL_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '国募集状況詳細id',
	COUNTRY_RECRUITMENT_ID INT UNSIGNED NOT NULL COMMENT '国募集状況id',
	ITEM_NAME VARCHAR(20) NOT NULL COMMENT '項目名',
	ITEM_VALUE VARCHAR(1000) NOT NULL COMMENT '項目値',
	PRIMARY KEY (COUNTRY_RECRUITMENT_DETAIL_ID)
) COMMENT = '国募集状況詳細';


CREATE TABLE PLAYER
(
	PLAYER_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'プレイヤーID',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時',
	REGISTER_TRACE VARCHAR(64) NOT NULL COMMENT '登録トレース',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時',
	UPDATE_TRACE VARCHAR(64) NOT NULL COMMENT '更新トレース',
	PRIMARY KEY (PLAYER_ID)
) COMMENT = 'プレイヤー';


CREATE TABLE RECRUIT_STATS
(
	RECRUIT_STATS_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '開催状況統計id',
	STATS_DATETIME DATETIME NOT NULL COMMENT '日時',
	VILLAGE_NUM INT UNSIGNED NOT NULL COMMENT '村数',
	PARTICIPATE_NUM INT UNSIGNED NOT NULL COMMENT '参加者数',
	PRIMARY KEY (RECRUIT_STATS_ID)
) COMMENT = '開催状況統計';


CREATE TABLE VILLAGE
(
	VILLAGE_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '村ID',
	COUNTRY_ID INT UNSIGNED NOT NULL COMMENT '国ID',
	VILLAGE_NAME VARCHAR(255) NOT NULL COMMENT '村名',
	VILLAGE_NO INT UNSIGNED NOT NULL COMMENT '村番号',
	VILLAGE_URL VARCHAR(255) NOT NULL COMMENT '村URL',
	VILLAGE_START_DATETIME DATETIME COMMENT '開始日時',
	VILLAGE_END_DATETIME DATETIME COMMENT '終了日時',
	WIN_CAMP_NAME VARCHAR(255) COMMENT '勝利陣営名',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時',
	REGISTER_TRACE VARCHAR(64) NOT NULL COMMENT '登録トレース',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時',
	UPDATE_TRACE VARCHAR(64) NOT NULL COMMENT '更新トレース',
	PRIMARY KEY (VILLAGE_ID)
) COMMENT = '村';


CREATE TABLE VILLAGE_PLAYER_STATS
(
	VILLAGE_PLAYER_STATS_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '村戦績ID',
	COUNTRY_PLAYER_ID INT UNSIGNED NOT NULL COMMENT '国プレイヤーID',
	VILLAGE_ID INT UNSIGNED NOT NULL COMMENT '村ID',
	CHARACTER_NAME VARCHAR(255) NOT NULL COMMENT 'キャラクター名',
	SKILL_NAME VARCHAR(255) NOT NULL COMMENT '役職名',
	WINLOSE_CODE VARCHAR(20) COMMENT '勝敗コード',
	LIFE VARCHAR(20) COMMENT '生死',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時',
	REGISTER_TRACE VARCHAR(64) NOT NULL COMMENT '登録トレース',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時',
	UPDATE_TRACE VARCHAR(64) NOT NULL COMMENT '更新トレース',
	PRIMARY KEY (VILLAGE_PLAYER_STATS_ID),
	CONSTRAINT UQ_village_player_stats_player_village UNIQUE (COUNTRY_PLAYER_ID, VILLAGE_ID)
) COMMENT = '村戦績';


CREATE TABLE WINLOSE
(
	WINLOSE_CODE VARCHAR(20) NOT NULL COMMENT '勝敗コード',
	WINLOSE_NAME VARCHAR(255) NOT NULL COMMENT '勝敗名',
	PRIMARY KEY (WINLOSE_CODE)
) COMMENT = '勝敗';



/* Create Foreign Keys */

ALTER TABLE COUNTRY_PLAYER
	ADD CONSTRAINT FK_COUNTRY_PLAYER_COUNTRY FOREIGN KEY (COUNTRY_ID)
	REFERENCES COUNTRY (COUNTRY_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE COUNTRY_PROGRESS
	ADD CONSTRAINT FK_COUNTRY_PROGRESS_COUNTRY FOREIGN KEY (COUNTRY_ID)
	REFERENCES COUNTRY (COUNTRY_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE COUNTRY_RECRUITMENT
	ADD CONSTRAINT FK_COUNTRY_RECRUITMENT_HEADER_COUNTRY FOREIGN KEY (COUNTRY_ID)
	REFERENCES COUNTRY (COUNTRY_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE VILLAGE
	ADD CONSTRAINT FK_VILLAGE_COUNTRY FOREIGN KEY (COUNTRY_ID)
	REFERENCES COUNTRY (COUNTRY_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE VILLAGE_PLAYER_STATS
	ADD CONSTRAINT FK_VILLAGE_PLAYER_STATS_COUNTRY_PLAYER FOREIGN KEY (COUNTRY_PLAYER_ID)
	REFERENCES COUNTRY_PLAYER (COUNTRY_PLAYER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE COUNTRY_PROGRESS_DETAIL
	ADD CONSTRAINT FK_COUNTRY_PROGRESS_DETAIL_COUNTRY_PROGRESS FOREIGN KEY (COUNTRY_PROGRESS_ID)
	REFERENCES COUNTRY_PROGRESS (COUNTRY_PROGRESS_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE COUNTRY_RECRUITMENT_DETAIL
	ADD CONSTRAINT FK_COUNTRY_RECRUITMENT_DETAIL_COUNTRY_RECRUITMENT FOREIGN KEY (COUNTRY_RECRUITMENT_ID)
	REFERENCES COUNTRY_RECRUITMENT (COUNTRY_RECRUITMENT_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE COUNTRY_PLAYER
	ADD CONSTRAINT FK_COUNTRY_PLAYER_PLAYER FOREIGN KEY (PLAYER_ID)
	REFERENCES PLAYER (PLAYER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE VILLAGE_PLAYER_STATS
	ADD CONSTRAINT FK_VILLAGE_PLAYER_STATS_VILLAGE FOREIGN KEY (VILLAGE_ID)
	REFERENCES VILLAGE (VILLAGE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE VILLAGE_PLAYER_STATS
	ADD CONSTRAINT FK_VILLAGE_PLAYER_STATS_WINLOSE FOREIGN KEY (WINLOSE_CODE)
	REFERENCES WINLOSE (WINLOSE_CODE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



