spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${WOLF_PORTAL_DB_NAME}?characterEncoding=UTF-8
    username: ${WOLF_PORTAL_DB_USERNAME}
    password: ${WOLF_PORTAL_DB_PASSWORD}
    driverClassName: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    mode: HTML
  messages:
    basename: messages
    cache-seconds: -1
    encoding: UTF-8
server:
  port: 8080
  servlet:
    session:
      timeout: 86400
logging:
  level:
    org.springframework: INFO
    root: INFO
    org.seasar.dbflute: ERROR
  file: /var/log/wolf-portal/tomcat.log
