spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wportaldb?characterEncoding=UTF-8&useSSL=false
    username: wportaluser
    password: wportalpass
    driverClassName: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    mode: HTML
  messages:
    basename: messages
    cache-seconds: -1
    encoding: UTF-8
server:
  port: 8080
  servlet:
    session:
      timeout: 86400
logging:
  level:
    org.springframework: INFO
    root: INFO
    org.seasar.dbflute: ERROR
  file: /var/log/wolf-portal/tomcat.log
