name: delivery_oracle

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: clone repository
        uses: actions/checkout@v7

      - name: set up JDK 11
        uses: actions/setup-java@v5
        with:
          distribution: 'microsoft'
          java-version: '11'

      - name: build
        run: |
          ./gradlew jibDockerBuild

      - name: push image
        run: |
          echo "${{ secrets.PACKAGE_PAT }}" | docker login ghcr.io -u h-orito --password-stdin
          docker push ghcr.io/h-orito/wolf-portal

  release:
    needs: build
    runs-on: [ self-hosted ]
    steps:
      - name: install kubectl
        run: |
          curl -sSLo $RUNNER_TEMP/kubectl "https://dl.k8s.io/release/$(curl -sSL https://dl.k8s.io/release/stable.txt)/bin/linux/arm64/kubectl"
          chmod +x $RUNNER_TEMP/kubectl

      - name: rollout restart
        run: |
          $RUNNER_TEMP/kubectl rollout restart deployment wolf-portal
